file_read=open('Codingal.txt','r')
print("File in Read Mode-")
print(file_read.read())
file_read.close()
file_write=open('Codingal.txt','w')
print("File in Write Mode-")
print(file_write.write())
file_write.write("Hi I am enguin and i am 1 year old.")
file_append=open('Codingal.txt','a')
print("\n File in Append Mode-")
file_append.write("Hi I am enguin and i am 1 year old.")
file_append.close()